/*
 * generated by Xtext 2.30.0
 */
package de.fraunhofer.ipa.targetEnvironment.ide.contentassist.antlr;

import de.fraunhofer.ipa.targetEnvironment.ide.contentassist.antlr.internal.InternalBaseParser;
import org.antlr.runtime.Token;
import org.antlr.runtime.TokenSource;
import org.eclipse.xtext.parser.antlr.AbstractIndentationTokenSource;

public class BaseTokenSource extends AbstractIndentationTokenSource {

	public BaseTokenSource(TokenSource delegate) {
		super(delegate);
	}

	@Override
	protected boolean shouldSplitTokenImpl(Token token) {
		// TODO Review assumption
		return token.getType() == InternalBaseParser.RULE_WS;
	}

	@Override
	protected int getBeginTokenType() {
		// TODO Review assumption
		return InternalBaseParser.RULE_INDENT;
	}

	@Override
	protected int getEndTokenType() {
		// TODO Review assumption
		return InternalBaseParser.RULE_DEDENT;
	}

	@Override
	protected boolean shouldEmitPendingEndTokens() {
		return false;
	}
}
