/*
 * generated by Xtext 2.30.0
 */
package de.fraunhofer.ipa.deployment.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class UtilUiModule extends AbstractUtilUiModule {

    public UtilUiModule(AbstractUIPlugin plugin) {
        super(plugin);
    }
}
