<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="util" nsURI="http://www.ipa.fraunhofer.de/Util" nsPrefix="Util">
  <eClassifiers xsi:type="ecore:EClass" name="Description" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="PropertyValue" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="PropertyValueInt" eSuperTypes="#//PropertyValue">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Int"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PropertyValueDouble" eSuperTypes="#//PropertyValue">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Double"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PropertyValueString" eSuperTypes="#//PropertyValue">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PropertyType" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractProperty" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractResouceType" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="ProcessorArchitecture" abstract="true"
      eSuperTypes="#//AbstractResouceType"/>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractCommunicationType" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="CommunicationType" eSuperTypes="#//AbstractCommunicationType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="Ethernet"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NetworkCommunicationType" abstract="true"
      eSuperTypes="#//AbstractCommunicationType"/>
  <eClassifiers xsi:type="ecore:EClass" name="EthernetCommunicationType" eSuperTypes="#//NetworkCommunicationType"/>
  <eClassifiers xsi:type="ecore:EClass" name="WlanCommunicationType" eSuperTypes="#//NetworkCommunicationType"/>
  <eClassifiers xsi:type="ecore:EClass" name="AvailableResouce">
    <eStructuralFeatures xsi:type="ecore:EReference" name="list" upperBound="-1" eType="#//AbstractResouceType"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="property" eType="#//AbstractProperty"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OpertingSystemType" abstract="true"
      eSuperTypes="#//AbstractResouceType"/>
  <eClassifiers xsi:type="ecore:EClass" name="LinuxOpertingSystemType" eSuperTypes="#//OpertingSystemType"/>
  <eClassifiers xsi:type="ecore:EClass" name="MacOSOpertingSystemType" eSuperTypes="#//OpertingSystemType"/>
  <eClassifiers xsi:type="ecore:EClass" name="ProcessorArchitectureType" eSuperTypes="#//AbstractResouceType"/>
  <eClassifiers xsi:type="ecore:EClass" name="ProcessorArchitectureValue" abstract="true"
      eSuperTypes="#//PropertyValue"/>
  <eClassifiers xsi:type="ecore:EClass" name="X86ProcessorArchitecture" eSuperTypes="#//ProcessorArchitectureValue"/>
  <eClassifiers xsi:type="ecore:EClass" name="Arm64ProcessorArchitecture" eSuperTypes="#//ProcessorArchitectureValue"/>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractImplementation" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractComputationAssignmentTarget"
      abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="PropertyKind" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="AttributeKind" eSuperTypes="#//PropertyKind"/>
  <eClassifiers xsi:type="ecore:EClass" name="MaximumKind" eSuperTypes="#//PropertyKind"/>
  <eClassifiers xsi:type="ecore:EClass" name="MinimumKind" eSuperTypes="#//PropertyKind"/>
  <eClassifiers xsi:type="ecore:EClass" name="SelectionKind" eSuperTypes="#//PropertyKind"/>
  <eClassifiers xsi:type="ecore:EClass" name="RangeKind" eSuperTypes="#//PropertyKind"/>
  <eClassifiers xsi:type="ecore:EClass" name="PropertyAttribute" eSuperTypes="#//AbstractProperty">
    <eStructuralFeatures xsi:type="ecore:EReference" name="kind" lowerBound="1" eType="#//AttributeKind"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//PropertyValue"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PropertyMaximun" eSuperTypes="#//AbstractProperty">
    <eStructuralFeatures xsi:type="ecore:EReference" name="kind" lowerBound="1" eType="#//MaximumKind"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//PropertyValue"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PropertyMinimum" eSuperTypes="#//AbstractProperty">
    <eStructuralFeatures xsi:type="ecore:EReference" name="kind" lowerBound="1" eType="#//MinimumKind"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//PropertyValue"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PropertySelection" eSuperTypes="#//AbstractProperty">
    <eStructuralFeatures xsi:type="ecore:EReference" name="kind" lowerBound="1" eType="#//SelectionKind"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" upperBound="-1"
        eType="#//PropertyValue" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PropertyRange" eSuperTypes="#//AbstractProperty">
    <eStructuralFeatures xsi:type="ecore:EReference" name="kind" lowerBound="1" eType="#//RangeKind"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" upperBound="2" eType="#//PropertyValue"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Property" eSuperTypes="#//AbstractProperty">
    <eStructuralFeatures xsi:type="ecore:EReference" name="kind" lowerBound="1" eType="#//PropertyKind"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" upperBound="2" eType="#//PropertyValue"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ResourceType" eSuperTypes="#//AbstractResouceType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
