/*
 * generated by Xtext 2.30.0
 */
package de.fraunhofer.ipa.deplyoment.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import de.fraunhofer.ipa.deplyoment.PlanRuntimeModule;
import de.fraunhofer.ipa.deplyoment.PlanStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class PlanIdeSetup extends PlanStandaloneSetup {

    @Override
    public Injector createInjector() {
        return Guice.createInjector(Modules2.mixin(new PlanRuntimeModule(), new PlanIdeModule()));
    }

}
