version: '3'
networks:
  ros-network:
    external: false
    driver: "bridge"
  ur5e:
    driver: macvlan
    driver_opts:
      parent: enp0s31f6
    ipam:
      driver: default

services:
  bt_operator:
    image: ${Registry}/bt_operator:latest
    volumes:
      - ./cyclonedds.xml:/cyclonedds.xml
    networks:
      - ros-network
    environment:
      - NETINTERFACE=eth0
      - use_sim_time=false
    command:
      - bash
      - -c
      - |
        export CYCLONEDDS_URI=file:///cyclonedds.xml
        source /ros_entrypoint.sh
        ros2 launch man2_bt_operator bringup_tree.launch.py use_sim_time:=false
