/*
 * generated by Xtext 2.35.0
 */
package de.fraunhofer.ipa.deployment.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractUtilScopeProvider extends DelegatingScopeProvider {
}
