<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="device" nsURI="http://www.ipa.fraunhofer.de/Device" nsPrefix="Device">
  <eClassifiers xsi:type="ecore:EClass" name="DeviceSet" eSuperTypes="../../de.fraunhofer.ipa.deployment.util/model/util.ecore#//Description">
    <eStructuralFeatures xsi:type="ecore:EReference" name="device" lowerBound="1"
        upperBound="-1" eType="#//DeviceType" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DeviceType" eSuperTypes="#//AbstractDeviceType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="deviceResource" upperBound="-1"
        eType="#//DeviceResource" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DeviceResource" eSuperTypes="../../de.fraunhofer.ipa.deployment.util/model/util.ecore#//Resource"/>
  <eClassifiers xsi:type="ecore:EClass" name="CommunicationConnection" eSuperTypes="#//AbstractCommunicationConnection">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="ecore:EClass ../../de.fraunhofer.ipa.deployment.util/model/util.ecore#//CommunicationType"
        derived="true" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1"
        eType="#//AbstractConnectionProperty" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConnectionProperty" eSuperTypes="../../de.fraunhofer.ipa.deployment.util/model/util.ecore#//PropertyAttribute #//AbstractConnectionProperty"/>
  <eClassifiers xsi:type="ecore:EClass" name="ComputationDeviceType" eSuperTypes="#//DeviceType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="computationResource" lowerBound="1"
        upperBound="-1" eType="#//AbstractComputationResource" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NetworkConnection" eSuperTypes="#//AbstractCommunicationConnection">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="ecore:EClass ../../de.fraunhofer.ipa.deployment.util/model/util.ecore#//NetworkCommunicationType"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1"
        eType="#//AbstractNetworkProperty" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InterfaceNetworkProperty" eSuperTypes="../../de.fraunhofer.ipa.deployment.util/model/util.ecore#//PropertyAttribute #//AbstractNetworkProperty"/>
  <eClassifiers xsi:type="ecore:EClass" name="AddressNetworkProperty" eSuperTypes="../../de.fraunhofer.ipa.deployment.util/model/util.ecore#//PropertyAttribute #//AbstractNetworkProperty"/>
  <eClassifiers xsi:type="ecore:EClass" name="MacAddressNetworkProperty" eSuperTypes="../../de.fraunhofer.ipa.deployment.util/model/util.ecore#//PropertyAttribute #//AbstractNetworkProperty"/>
  <eClassifiers xsi:type="ecore:EClass" name="PortNetworkProperty" eSuperTypes="../../de.fraunhofer.ipa.deployment.util/model/util.ecore#//PropertyAttribute #//AbstractNetworkProperty"/>
  <eClassifiers xsi:type="ecore:EClass" name="IdentityNameNetworkProperty" eSuperTypes="../../de.fraunhofer.ipa.deployment.util/model/util.ecore#//PropertyAttribute #//AbstractNetworkProperty"/>
  <eClassifiers xsi:type="ecore:EClass" name="GatewayNetworkProperty" eSuperTypes="../../de.fraunhofer.ipa.deployment.util/model/util.ecore#//PropertyAttribute #//AbstractNetworkProperty"/>
  <eClassifiers xsi:type="ecore:EClass" name="SubnetMaskNetworkProperty" eSuperTypes="../../de.fraunhofer.ipa.deployment.util/model/util.ecore#//PropertyAttribute #//AbstractNetworkProperty"/>
  <eClassifiers xsi:type="ecore:EClass" name="DNSServerNetworkProperty" eSuperTypes="../../de.fraunhofer.ipa.deployment.util/model/util.ecore#//PropertySelection #//AbstractNetworkProperty"/>
  <eClassifiers xsi:type="ecore:EClass" name="UsbConnection" eSuperTypes="#//AbstractCommunicationConnection">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="ecore:EClass ../../de.fraunhofer.ipa.deployment.util/model/util.ecore#//UsbCommunicationType"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1"
        eType="#//AbstractUsbProperty" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DeviceVolumeUsbProperty" eSuperTypes="../../de.fraunhofer.ipa.deployment.util/model/util.ecore#//PropertySelection #//AbstractUsbProperty"/>
  <eClassifiers xsi:type="ecore:EClass" name="Container" eSuperTypes="#//AbstractRuntimeEnviroment"/>
  <eClassifiers xsi:type="ecore:EClass" name="OperatingSystemResouce" eSuperTypes="#//AbstractComputationResource">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="ecore:EClass ../../de.fraunhofer.ipa.deployment.util/model/util.ecore#//OpertingSystemResouceType"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1"
        eType="#//AbstractOperatingSystemProperty" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NameOperatingSystemProperty" eSuperTypes="../../de.fraunhofer.ipa.deployment.util/model/util.ecore#//PropertyAttribute #//AbstractOperatingSystemProperty"/>
  <eClassifiers xsi:type="ecore:EClass" name="VersionOperatingSystemProperty" eSuperTypes="../../de.fraunhofer.ipa.deployment.util/model/util.ecore#//PropertyAttribute #//AbstractOperatingSystemProperty"/>
  <eClassifiers xsi:type="ecore:EClass" name="ProcessorResouce" eSuperTypes="#//AbstractComputationResource">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="ecore:EClass ../../de.fraunhofer.ipa.deployment.util/model/util.ecore#//ProcessorResouceType"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1"
        eType="#//AbstracProcessorProperty" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ArchitectureProcessorProperty" eSuperTypes="../../de.fraunhofer.ipa.deployment.util/model/util.ecore#//PropertyAttribute #//AbstracProcessorProperty"/>
  <eClassifiers xsi:type="ecore:EClass" name="CoreProcessorProperty" eSuperTypes="../../de.fraunhofer.ipa.deployment.util/model/util.ecore#//PropertyAttribute #//AbstracProcessorProperty"/>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractNetworkProperty" abstract="true"
      eSuperTypes="#//AbstractConnectionProperty"/>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractUsbProperty" abstract="true"
      eSuperTypes="#//AbstractConnectionProperty"/>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractCommunicationConnection" abstract="true"
      eSuperTypes="../../de.fraunhofer.ipa.deployment.util/model/util.ecore#//AbstractResource"/>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractRuntimeEnviroment" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractOperatingSystemProperty" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="AbstracProcessorProperty" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractComputationResource" abstract="true"
      eSuperTypes="../../de.fraunhofer.ipa.deployment.util/model/util.ecore#//AbstractResource"/>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractDeviceType" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="communicationConnection"
        upperBound="-1" eType="#//AbstractCommunicationConnection" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractConnectionProperty" abstract="true"/>
</ecore:EPackage>
