<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="targetEnvironment" nsURI="http://www.ipa.fraunhofer.de/TargetEnvironment"
    nsPrefix="TargetEnvironment">
  <eClassifiers xsi:type="ecore:EClass" name="TargetEnvironment">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" upperBound="-1"
        eType="ecore:EClass ../../de.fraunhofer.ipa.deployment.util/model/util.ecore#//Description"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TargetDeployEnviroment" eSuperTypes="../../de.fraunhofer.ipa.deployment.util/model/util.ecore#//Description">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="includeDevice" upperBound="-1"
        eType="#//AbstractDeviceInstance" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="configConnections" upperBound="-1"
        eType="#//ConfigConnection" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConfigConnection">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="connectDevice" lowerBound="2"
        upperBound="-1" eType="#//ConnectedDevice" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConnectedDevice">
    <eStructuralFeatures xsi:type="ecore:EReference" name="refDevice" lowerBound="1"
        eType="#//AbstractDeviceInstance"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="refConnection" lowerBound="1"
        eType="ecore:EClass device.ecore#//AbstractCommunicationConnection"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1"
        eType="#//ConfigConnectionProperty" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConfigConnectionProperty" eSuperTypes="#//AbstractConfigProperty">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="refConnectionProperty"
        lowerBound="1" eType="ecore:EClass device.ecore#//AbstractConnectionProperty"
        derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" lowerBound="1" eType="ecore:EClass ../../de.fraunhofer.ipa.deployment.util/model/util.ecore#//PropertyValue"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ComputationDeviceInstance" eSuperTypes="#//AbstractDeviceInstance">
    <eStructuralFeatures xsi:type="ecore:EReference" name="refDeviceType" lowerBound="1"
        eType="ecore:EClass device.ecore#//ComputationDeviceType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DeviceInstance" eSuperTypes="#//AbstractDeviceInstance">
    <eStructuralFeatures xsi:type="ecore:EReference" name="refDeviceType" lowerBound="1"
        eType="ecore:EClass device.ecore#//DeviceType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConfigDeviceProperty" eSuperTypes="#//AbstractConfigProperty">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="refProperty" lowerBound="1"
        eType="ecore:EClass ../../de.fraunhofer.ipa.deployment.util/model/util.ecore#//AbstractProperty"
        derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" lowerBound="1" eType="ecore:EClass ../../de.fraunhofer.ipa.deployment.util/model/util.ecore#//PropertyValue"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractDeviceInstance" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="configDeviceProperty" upperBound="-1"
        eType="#//ConfigDeviceProperty" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractConfigProperty" abstract="true"/>
</ecore:EPackage>
