<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="deploymentPlan" nsURI="http://www.ipa.fraunhofer.de/DeploymentPlan"
    nsPrefix="DeploymentPlan">
  <eClassifiers xsi:type="ecore:EClass" name="Plan">
    <eStructuralFeatures xsi:type="ecore:EReference" name="plan" lowerBound="1" eType="#//AbstractDeploymentPlan"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DeploymentPlan" eSuperTypes="#//AbstractDeploymentPlan"/>
  <eClassifiers xsi:type="ecore:EClass" name="Realization" abstract="true" interface="true"
      eSuperTypes="#//AbstractRealization"/>
  <eClassifiers xsi:type="ecore:EClass" name="ImplementationAssignment" eSuperTypes="#//AbstractComputationAssignment"/>
  <eClassifiers xsi:type="ecore:EClass" name="ConfigExecutionParameter" eSuperTypes="#//AbstractConfigExecutionParameter">
    <eStructuralFeatures xsi:type="ecore:EReference" name="from" lowerBound="1" eType="ecore:EClass ImplementationDescription.ecore#//ExecutionParameter"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="to" eType="ecore:EClass ../../de.fraunhofer.ipa.targetEnvironment/model/targetEnvironment.ecore#//AbstractConfigProperty"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="ecore:EClass ../../de.fraunhofer.ipa.deployment.util/model/util.ecore#//PropertyValue"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Middleware" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="ConfigSoftwareComponent" eSuperTypes="#//AbstarctConfigSoftwareComponent">
    <eStructuralFeatures xsi:type="ecore:EReference" name="component" lowerBound="1"
        eType="ecore:EClass ../../de.fraunhofer.ipa.deployment.util/model/util.ecore#//AbstractComputationAssignmentTarget"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractRealization" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="realizations" upperBound="-1"
        eType="#//AbstractComputationAssignment" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractConfigExecutionParameter" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractComputationAssignment" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="executedBy" lowerBound="1"
        eType="ecore:EClass ../../de.fraunhofer.ipa.targetEnvironment/model/targetEnvironment.ecore#//ComputationDeviceInstance"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="softwareComponents" lowerBound="1"
        upperBound="-1" eType="#//AbstarctConfigSoftwareComponent" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="middleware" eType="#//Middleware"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="runtimeType" eType="#//AbstractRuntime"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractDeploymentPlan" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="deployTo" lowerBound="1"
        eType="ecore:EClass ../../de.fraunhofer.ipa.targetEnvironment/model/targetEnvironment.ecore#//TargetDeployEnviroment"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="realize" lowerBound="1"
        eType="#//AbstractRealization" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstarctConfigSoftwareComponent" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="executionConfiguration"
        upperBound="-1" eType="#//AbstractConfigExecutionParameter" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="startCommand" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ROSDistro">
    <eLiterals name="humble" value="2"/>
    <eLiterals name="noetic" value="1"/>
    <eLiterals name="rolling" value="2"/>
    <eLiterals name="galactic" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RosMiddleware" eSuperTypes="#//Middleware">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="#//ROSDistro"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractRuntime" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="ecore:EEnum ../../de.fraunhofer.ipa.deployment.util/model/util.ecore#//RunTimeType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ContainerRuntime" eSuperTypes="#//AbstractRuntime">
    <eStructuralFeatures xsi:type="ecore:EReference" name="opertingSystemResource"
        upperBound="2" eType="ecore:EClass ../../de.fraunhofer.ipa.deployment.util/model/util.ecore#//OperatingSystemResouce"
        containment="true"/>
  </eClassifiers>
</ecore:EPackage>
