  - name: Make sure docker-compose file is present
    ansible.builtin.stat:
      path: "{{ ori_docker_compose_dir_path }}/{{ item }}"
    loop:
      - cyclonedds.xml
      - docker-compose.yaml

  - name: Make sure destination dir exists
    become: true
    file:
      path: "{{ dest_docker_compose_dir_path }}"
      state: directory
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user }}"

  - name: Copy compose files
    ansible.builtin.copy:
      src: "{{ ori_docker_compose_dir_path }}/{{ item }}"
      dest: "{{ dest_docker_compose_dir_path }}/{{ item }}"
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user }}"
      mode: "0644"
    loop:
      - cyclonedds.xml
      - docker-compose.yaml

  - name: Tear down existing "bt_framework_ur5e" service
    community.general.docker_compose:
      project_src: "{{ dest_docker_compose_dir_path }}"
      stopped: true
      state: present
      services:
        - bt_framework_ur5e
    tags:
      - stop_service
      - bt_framework_ur5e
      - cmh_tower_400
    register: output

  - name: Create and start "bt_framework_ur5e" service
    community.general.docker_compose:
      project_src: "{{ dest_docker_compose_dir_path }}"
      pull: true
      services:
        - bt_framework_ur5e
    tags:
      - start_service
      - bt_framework_ur5e
      - cmh_tower_400
    register: output

  - name: Tear down existing "launch_realsense" service
    community.general.docker_compose:
      project_src: "{{ dest_docker_compose_dir_path }}"
      stopped: true
      state: present
      services:
        - launch_realsense
    tags:
      - stop_service
      - launch_realsense
      - cmh_tower_400
    register: output

  - name: Create and start "launch_realsense" service
    community.general.docker_compose:
      project_src: "{{ dest_docker_compose_dir_path }}"
      pull: true
      services:
        - launch_realsense
    tags:
      - start_service
      - launch_realsense
      - cmh_tower_400
    register: output

  - name: Tear down existing "aruco_marker_detectionm" service
    community.general.docker_compose:
      project_src: "{{ dest_docker_compose_dir_path }}"
      stopped: true
      state: present
      services:
        - aruco_marker_detectionm
    tags:
      - stop_service
      - aruco_marker_detectionm
      - cmh_tower_400
    register: output

  - name: Create and start "aruco_marker_detectionm" service
    community.general.docker_compose:
      project_src: "{{ dest_docker_compose_dir_path }}"
      pull: true
      services:
        - aruco_marker_detectionm
    tags:
      - start_service
      - aruco_marker_detectionm
      - cmh_tower_400
    register: output

  - name: Tear down existing "ur_driver_with_moveit" service
    community.general.docker_compose:
      project_src: "{{ dest_docker_compose_dir_path }}"
      stopped: true
      state: present
      services:
        - ur_driver_with_moveit
    tags:
      - stop_service
      - ur_driver_with_moveit
      - cmh_tower_400
    register: output

  - name: Create and start "ur_driver_with_moveit" service
    community.general.docker_compose:
      project_src: "{{ dest_docker_compose_dir_path }}"
      pull: true
      services:
        - ur_driver_with_moveit
    tags:
      - start_service
      - ur_driver_with_moveit
      - cmh_tower_400
    register: output

  - name: Debug output
    ansible.builtin.debug:
      var: output
