/*
 * generated by Xtext 2.30.0
 */
package de.fraunhofer.ipa.deplyoment.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import de.fraunhofer.ipa.deplyoment.PlanWithRosmodelRuntimeModule;
import de.fraunhofer.ipa.deplyoment.PlanWithRosmodelStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class PlanWithRosmodelIdeSetup extends PlanWithRosmodelStandaloneSetup {

    @Override
    public Injector createInjector() {
        return Guice.createInjector(Modules2.mixin(new PlanWithRosmodelRuntimeModule(), new PlanWithRosmodelIdeModule()));
    }

}
