/*
 * generated by Xtext 2.30.0
 */
package de.fraunhofer.ipa.deployment;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class ImplementationDescriptionStandaloneSetup extends ImplementationDescriptionStandaloneSetupGenerated {

    public static void doSetup() {
        new ImplementationDescriptionStandaloneSetup().createInjectorAndDoEMFRegistration();
    }
}
