/*
 * generated by Xtext 2.30.0
 */
package de.fraunhofer.ipa.deployment;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class PlanStandaloneSetup extends PlanStandaloneSetupGenerated {

    public static void doSetup() {
        new PlanStandaloneSetup().createInjectorAndDoEMFRegistration();
    }
}
