/*
 * generated by Xtext 2.35.0
 */
package de.fraunhofer.ipa.deployment.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractUtilValidator extends AbstractDeclarativeValidator {

  @Override
  protected List<EPackage> getEPackages() {
    List<EPackage> result = new ArrayList<EPackage>();
    result.add(EPackage.Registry.INSTANCE.getEPackage("http://www.ipa.fraunhofer.de/Util"));
    return result;
  }
}
