/*
 * generated by Xtext 2.30.0
 */
package de.fraunhofer.ipa.targetEnvironment.ide;


/**
 * Use this class to register ide components.
 */
public class BaseIdeModule extends AbstractBaseIdeModule {
}
