/*
 * generated by Xtext 2.30.0
 */
package de.fraunhofer.ipa.targetEnvironment.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class BaseUiModule extends AbstractBaseUiModule {

	public BaseUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
